# Generated by Django 4.0.5 on 2022-06-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000, max_length=4),
        ),
    ]
