# Generated by Django 4.0.5 on 2022-06-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0003_move_description_move_imdb_rating_move_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfoToMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('genre', models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (1, 'Horror'), (4, 'Dramat'), (2, 'Komedia'), (0, 'Inne'), (5, 'Akcji')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='extra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kinoweb.extrainfotomovie'),
        ),
    ]
