# Generated by Django 4.0.5 on 2022-06-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0004_extrainfotomovie_move_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfotomovie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (1, 'Horror'), (4, 'Dramat'), (5, 'Akcji'), (2, 'Komedia'), (3, 'Sci-fi')], default=0),
        ),
        migrations.CreateModel(
            name='RatingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textReview', models.TextField(blank=True, default='')),
                ('stars', models.PositiveSmallIntegerField(blank=True, default=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoweb.move')),
            ],
        ),
    ]
