# Generated by Django 4.0.5 on 2022-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0005_alter_extrainfotomovie_genre_ratingmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfotomovie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (5, 'Akcji'), (0, 'Inne'), (1, 'Horror'), (2, 'Komedia'), (4, 'Dramat')], default=0),
        ),
        migrations.AlterField(
            model_name='ratingmovie',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '☆'), (7, '☆☆☆☆☆☆☆'), (2, '☆☆'), (9, '☆☆☆☆☆☆☆☆☆'), (6, '☆☆☆☆☆☆'), (4, '☆☆☆☆'), (8, '☆☆☆☆☆☆☆☆'), (3, '☆☆☆'), (10, '☆☆☆☆☆☆☆☆☆☆'), (5, '☆☆☆☆☆')], default=10),
        ),
    ]
