# Generated by Django 4.0.5 on 2022-06-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0006_alter_extrainfotomovie_genre_alter_ratingmovie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfotomovie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Dramat'), (0, 'Inne'), (5, 'Akcji'), (1, 'Horror'), (3, 'Sci-fi'), (2, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='ratingmovie',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '☆'), (2, '☆☆'), (3, '☆☆☆'), (4, '☆☆☆☆'), (5, '☆☆☆☆☆'), (6, '☆☆☆☆☆☆'), (7, '☆☆☆☆☆☆☆'), (8, '☆☆☆☆☆☆☆☆'), (9, '☆☆☆☆☆☆☆☆☆'), (10, '☆☆☆☆☆☆☆☆☆☆')], default=10),
        ),
    ]
