# Generated by Django 4.0.5 on 2022-06-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0007_alter_extrainfotomovie_genre_alter_ratingmovie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfotomovie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Akcji'), (3, 'Sci-fi'), (1, 'Horror'), (2, 'Komedia'), (4, 'Dramat'), (0, 'Inne')], default=0),
        ),
        migrations.AlterField(
            model_name='ratingmovie',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1: ☆'), (2, '2: ☆☆'), (3, '3: ☆☆☆'), (4, '4: ☆☆☆☆'), (5, '5: ☆☆☆☆☆'), (6, '6: ☆☆☆☆☆☆'), (7, '7: ☆☆☆☆☆☆☆'), (8, '8: ☆☆☆☆☆☆☆☆'), (9, '9: ☆☆☆☆☆☆☆☆☆'), (10, '10: ☆☆☆☆☆☆☆☆☆☆')], default=10),
        ),
    ]
