# Generated by Django 4.0.5 on 2022-06-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0008_alter_extrainfotomovie_genre_alter_ratingmovie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfotomovie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Komedia'), (3, 'Sci-fi'), (5, 'Akcji'), (4, 'Dramat'), (1, 'Horror')], default=0),
        ),
    ]
