# Generated by Django 4.0.5 on 2022-06-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0009_alter_extrainfotomovie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmovie',
            name='userName',
            field=models.CharField(default='Anonim', max_length=64),
        ),
        migrations.AlterField(
            model_name='extrainfotomovie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (5, 'Akcji'), (4, 'Dramat')], default=0),
        ),
    ]
