# Generated by Django 4.0.5 on 2022-06-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoweb', '0010_ratingmovie_username_alter_extrainfotomovie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfotomovie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (0, 'Inne'), (3, 'Sci-fi'), (5, 'Akcji'), (1, 'Horror'), (4, 'Dramat')], default=0),
        ),
        migrations.AlterField(
            model_name='ratingmovie',
            name='userName',
            field=models.CharField(default='', max_length=64),
        ),
    ]
